name: Tests

on:
  push:
    branches:
      - ast-engine
  pull_request:
    branches:
      - ast-engine

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run tests
        run: python -m unittest